#!/bin/bash

pigs p 14 120
pigs pfs 14 20

#setting up start fan speed and Set GPIO PWM frequency



while true; do

#read temperature

temperatura=$(vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')


temp=${temperatura%.*}

echo "Temperatura:$temp"



if [ $temp -gt 50 ]
then
	echo "Wiecej niz 50"
	echo "Ustawiam pigs p 14 200"
	pigs p 14 200

elif [ $temp -gt 45 ]
then
	echo "Temp > 45"
	echo "Ustawiam pigs p 14 160"
	pigs p 14 160
	
elif [ $temp -gt 40 ]
then
	echo "Temp > 40"
	echo "Ustawiam pigs p 14 140"
	pigs p 14 140
	
elif [ $temp -gt 35 ]
then
	echo "Temp > 35"
	echo "Ustawiam pigs p 14 130"
	pigs p 14 130

elif [ $temp -gt 30 ]
then
	echo "Temp > 30"
	echo "Ustawiam pigs p 14 110"
	pigs p 14 110

fi


sleep 3
echo "*****************"



done
