#!/bin/bash

pigs p 14 120
pigs pfs 14 10

#setting up start fan speed and Set GPIO PWM frequency



while true; do

#read temperature

temperatura=$(vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')
echo "*****************"

temp=${temperatura%.*}
echo "Temperatura:$temp"

currenttime=$(date +%H:%M)
echo "Godzina: $currenttime"
if [[ "$currenttime" > "23:00" ]] || [[ "$currenttime" < "07:30" ]]; then
  temp=$((temp -= 5))
else
  temp=$((temp))
fi






if [ $temp -gt 50 ]
then
	echo "Wiecej niz 50"
	echo "Ustawiam pigs p 14 240"
	pigs p 14 240
	pigs pfs 14 40
	echo "Ustawiam pigs pfs 14 40"

elif [ $temp -gt 48 ]
then
	echo "Temp > 48"
	echo "Ustawiam pigs p 14 205"
	pigs p 14 205
	pigs pfs 14 30
	echo "Ustawiam pigs pfs 14 30"
	
elif [ $temp -gt 45 ]
then
	echo "Temp > 45"
	echo "Ustawiam pigs p 14 175"
	pigs p 14 175
	pigs pfs 14 30
	echo "Ustawiam pigs pfs 14 30"
	
elif [ $temp -gt 42 ]
then
	echo "Temp > 42"
	echo "Ustawiam pigs p 14 145"
	pigs p 14 145
	pigs pfs 14 20
	echo "Ustawiam pigs pfs 14 20"

elif [ $temp -gt 40 ]
then
	echo "Temp > 40"
	echo "Ustawiam pigs p 14 135"
	pigs p 14 135
	pigs pfs 14 20
	echo "Ustawiam pigs pfs 14 20"
	
elif [ $temp -gt 38 ]
then
	echo "Temp > 38"
	echo "Ustawiam pigs p 14 120"
	pigs p 14 120
	pigs pfs 14 20
	echo "Ustawiam pigs pfs 14 20"

elif [ $temp -gt 35 ]
then
	echo "Temp > 35"
	echo "Ustawiam pigs p 14 115"
	pigs p 14 115
	pigs pfs 14 10
	echo "Ustawiam pigs pfs 14 10"
	
elif [ $temp -gt 32 ]
then
	echo "Temp > 32"
	echo "Ustawiam pigs p 14 110"
	pigs p 14 110
	pigs pfs 14 10
	echo "Ustawiam pigs pfs 14 10"

elif [ $temp -gt 30 ]
then
	echo "Temp > 30"
	echo "Ustawiam pigs p 14 105"
	pigs p 14 105
	pigs pfs 14 10
	echo "Ustawiam pigs pfs 14 10"
	
elif [ $temp -lt 30 ]
then
	echo "Temp < 30"
	echo "Ustawiam pigs p 14 80"
	pigs p 14 80
	pigs pfs 14 10
	echo "Ustawiam pigs pfs 14 10"

fi

echo "*****************"
sleep 10




done
